# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61093670404275254de169d8e956007a"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "b4u-delivery"
handle = "b4u-delivery"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-a7fe1328.myshopify.com"
include_config_on_deploy = true
